version: "3.9"

networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge

volumes:
  db_data:
  joomla_data:
  grafana_data:
  nginx_logs:

services:
    database:
      image: postgres:16-alpine
      container_name: database
      restart: unless-stopped
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
        - db_data:/var/lib/postgresql/data
      networks:
        - backend_net
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
        interval: 5s
        timeout: 5s
        retries: 10 
    joomla:
    image: joomla:latest
    container_name: joomla
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      JOOMLA_DB_HOST: database
      JOOMLA_DB_TYPE: pgsql
      JOOMLA_DB_NAME: ${POSTGRES_DB}
      JOOMLA_DB_USER: ${POSTGRES_USER}
      JOOMLA_DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - joomla_data:/var/www/html
      - nginx_logs:/var/log/apache2
    networks:
      - frontend_net
      - backend_net