networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge

volumes:
  db_data:
  joomla_data:
  grafana_data:
  nginx_logs:

services:
  database:
    image: postgres:16-alpine
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust" # Permite conexiones internas sin exigir contraseña
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10

  joomla:
    image: joomla:latest
    container_name: joomla
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      JOOMLA_DB_HOST: database
      JOOMLA_DB_TYPE: pgsql
      JOOMLA_DB_NAME: ${POSTGRES_DB}
      JOOMLA_DB_USER: ${POSTGRES_USER}
      JOOMLA_DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - joomla_data:/var/www/html
      - nginx_logs:/var/log/apache2
    networks:
      - frontend_net
      - backend_net

  jupyter:
    image: jupyter/minimal-notebook:latest
    container_name: jupyter
    restart: unless-stopped
    depends_on:
      - database
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
    networks:
      - frontend_net
      - backend_net
    # Desactiva los tokens de autenticación
    command: >
      start-notebook.sh --NotebookApp.base_url=/jupyter --NotebookApp.token='' --IdentityProvider.token=''

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - database
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"        # Habilita el acceso anónimo
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"       # Otorga permisos de Administrador directo
      GF_AUTH_DISABLE_LOGIN_FORM: "true"       # Oculta la pantalla de Inicio de Sesión
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - nginx_logs:/var/log/joomla:ro
    networks:
      - frontend_net
      - backend_net

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - joomla
      - jupyter
      - grafana
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_logs:/var/log/nginx
    networks:
      - frontend_net