apiVersion: 1

datasources:
  - name: PostgreSQL-Joomla
    type: postgres
    access: proxy
    url: database:5432
    user: joomlauser
    secureJsonData:
      password: joomlapass123
    jsonData:
      database: joomladb
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true